apiVersion: apps/v1
kind: Deployment
metadata:
  name: duc-nodejs-deployment
  namespace: python-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duc-nodejs-demo
  template:
    metadata:
      labels:
        app: duc-nodejs-demo
    spec:
      containers:
        - name: duc-nodejs-demo
          image: dangminhduc/devopstest:latest
          imagePullPolicy: "Always"
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_DATABASE
              value: your_database_name
            - name: DB_USERNAME
              value: your_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password

---
apiVersion: v1
kind: Service
metadata:
  name: duc-nodejs-demo-service
  namespace: python-demo
spec:
  ports:
    - port: 6302
      targetPort: 6302
  selector:
    app: duc-nodejs-demo
---

